name: Build native image
on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'
      - 'v*.*.*'
      - '*.*.*-*'
      - 'v*.*.*-*'
  pull_request:
    paths:
      - .github/**
      - src/**
      - project.clj
      - native-config/**

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: rinx/setup-graalvm-ce@v0.0.4
        with:
          graalvm-version: "20.1.0"
          java-version: "java11"
          native-image: "true"
      - name: echo versions
        run: |
          java -version
          native-image --version
      - name: Install dependencies
        run: |
          curl -o lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
          chmod a+x lein
          sudo apt-get update && sudo apt-get install -y upx
      - name: Build uberjar
        run: |
          ./lein uberjar
      - name: Build native image
        run: |
          make gitwerk
          upx -9 gitwerk
          zip --junk-paths gitwerk-linux-amd64 gitwerk
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: gitwerk-linux-amd64.zip
          path: ./gitwerk-linux-amd64.zip
  build-linux-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: rinx/setup-graalvm-ce@v0.0.4
        with:
          graalvm-version: "20.1.0"
          java-version: "java11"
          native-image: "true"
      - name: echo versions
        run: |
          java -version
          native-image --version
      - name: Install dependencies
        run: |
          curl -o lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
          chmod a+x lein
          sudo apt-get update && sudo apt-get install -y upx
      - name: Build uberjar
        run: |
          ./lein uberjar
      - name: Build native image
        run: |
          make gitwerk-static
          upx -9 gitwerk
          zip --junk-paths gitwerk-linux-static-amd64 gitwerk
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: gitwerk-linux-static-amd64.zip
          path: ./gitwerk-linux-static-amd64.zip
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install GraalVM
        run: |
          TMP_GRAALVM_HOME=/tmp/graalvm
          GRAALVM_HOME=/tmp/graalvm/Contents/Home
          GRAALVM_TGZ_URI="https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-${GRAALVM_VERSION}/graalvm-ce-${JAVA_VERSION}-darwin-amd64-${GRAALVM_VERSION}.tar.gz"
          curl -sL $GRAALVM_TGZ_URI --output graalvm.tar.gz
          mkdir -p $TMP_GRAALVM_HOME
          tar -xf graalvm.tar.gz -C $TMP_GRAALVM_HOME --strip-components=1
          chmod -R a+rwx $TMP_GRAALVM_HOME
          echo "::set-env name=PATH::$GRAALVM_HOME/bin:$PATH"
          echo "::set-env name=GRAALVM_HOME::$GRAALVM_HOME"
          echo "::set-env name=JAVA_HOME::$GRAALVM_HOME"
        env:
          GRAALVM_VERSION: 20.1.0
          JAVA_VERSION: java11
      - name: Install dependencies
        run: |
          brew install leiningen upx
          gu install native-image
      - name: Build uberjar
        run: |
          lein uberjar
      - name: Build native image
        run: |
          make
          upx -9 gitwerk
          zip --junk-paths gitwerk-macos-amd64 gitwerk
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: gitwerk-macos-amd64.zip
          path: ./gitwerk-macos-amd64.zip

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-linux-static, build-macos]
    steps:
      - uses: actions/checkout@v1
      - name: Create release
        if: startsWith( github.ref, 'refs/tags/')
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - uses: actions/download-artifact@v1
        if: startsWith( github.ref, 'refs/tags/')
        with:
          name: gitwerk-linux-amd64.zip
          path: tmp
      - name: Upload Release Asset (linux)
        if: startsWith( github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tmp/gitwerk-linux-amd64.zip
          asset_name: gitwerk-linux-amd64.zip
          asset_content_type: application/zip
      - uses: actions/download-artifact@v1
        if: startsWith( github.ref, 'refs/tags/')
        with:
          name: gitwerk-linux-static-amd64.zip
          path: tmp
      - name: Upload Release Asset (linux-static)
        if: startsWith( github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tmp/gitwerk-linux-static-amd64.zip
          asset_name: gitwerk-linux-static-amd64.zip
          asset_content_type: application/zip
      - uses: actions/download-artifact@v1
        if: startsWith( github.ref, 'refs/tags/')
        with:
          name: gitwerk-macos-amd64.zip
          path: tmp
      - name: Upload Release Asset (macos)
        if: startsWith( github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tmp/gitwerk-macos-amd64.zip
          asset_name: gitwerk-macos-amd64.zip
          asset_content_type: application/zip
