name: Build docker image
on:
  push:
    paths:
      - .github/workflows/docker.yml
      - Dockerfile
      - src/gitwerk/**
      - project.clj
      - reflection.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build -t gitwerk .
