name: Build docker image
on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'
      - 'v*.*.*'
      - '*.*.*-*'
      - 'v*.*.*-*'
  pull_request:
    paths:
      - .github/workflows/docker.yml
      - Dockerfile
      - src/gitwerk/**
      - project.clj
      - reflection.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build -t gitwerk . --build-arg GRAALVM_VERSION=${GRAALVM_VERSION}
      env:
        GRAALVM_VERSION: '19.3.1'
    - name: Login to DockerHub
      run: |
        echo ${DOCKERHUB_PASS} | docker login --username ${DOCKERHUB_USER} --password-stdin
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
    - name: push to DockerHub (master)
      if: github.ref == 'refs/heads/master'
      run: |
        docker tag gitwerk rinx/gitwerk:nightly
        docker push rinx/gitwerk:nightly
    - name: push to DockerHub (pull request)
      if: github.event_name == 'pull_request'
      run: |
        pr_num=`cat $GITHUB_EVENT_PATH | jq -r ".number"`
        docker tag gitwerk rinx/gitwerk:pr-${pr_num}
        docker push rinx/gitwerk:pr-${pr_num}
    - name: push to DockerHub (tags)
      if: startsWith( github.ref, 'refs/tags/')
      run: |
        tag_name=`echo $GITHUB_REF | sed -e 's:^refs/tags/::'`
        docker tag gitwerk rinx/gitwerk:${tag_name}
        docker push rinx/gitwerk:${tag_name}
